# Generated by Django 5.0.3 on 2025-03-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('proof_of_payment', models.ImageField(upload_to='payments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
